name 'Analytical Labs-artifactory'
version '1.0'

author 'Tom Barber'
license ''
project_page 'https://github.com/OSBI/puppet-artifactory'
source 'git@github.com:OSBI/puppet-artifactory.git'
summary 'A basic artifactory controller.'
description ''
dependency 'Analytical Labs/apache', '==1.0'
dependency 'Analytical Labs/tomcat', '==1.0'
dependency 'Analytical Labs/java', '==1.0'
