name 'Analytical Labs-artifactory'
version '1.0'

author 'Tom Barber'
license ''
project_page ''
source ''
summary ''
description ''
dependency 'Analytical Labs/apache', '==1.0'
dependency 'Analytical Labs/tomcat', '==1.0'
dependency 'Analytical Labs/java', '==1.0'
